reference: 'ARS.fa'
reference_uncompressed: 'ARS.fa'


repeat_masking: 'GCF_002263795.3.repeatMasker.out.gz'
reference_TRF: 'GCA_002263795.4_ARS-UCD2.0_genomic.trf.bed'
repeat_library: ''
short_reads: 'SR/'
sample_sheet: 'test_samples.csv'
